### ISSUE TITLE
Delayed::Job failure: Event 'mark_aged_out' cannot transition from 'delivered'

### ISSUE THREAD

**Issue by dgfitch** [uwmadison-chm/hedonometer#7]
bundle exec bin/rails console
    puts Delayed::Job.where('failed_at IS NULL').last.last_error
    ...
    Event 'mark_aged_out' cannot transition from 'delivered' ...

Possible race condition? Something is trying to mark a `delivered` ScheduledMessage as `aged_out`? The logic in `deliver_and_save_if_possible` might need a reversal, to check `too_old_to_deliver` first instead of falling through the delivery?

**Comment by dgfitch** [comment]
Looks like these failures are transitory, it went away while I looked at it. Heisenbug!

**Comment by njvack** [comment]
That's the thing I've seen before. We just don't want to mark a delivered message as aged_out? Is there a way a message could be scheduled for delivery more than once?

**Comment by dgfitch** [comment]
https://github.com/uwmadison-chm/hedonometer/blob/9e23b13c634f4c35db50ae69085fe43a238212d4/app/models/scheduled_message.rb#L83

I think that's getting called on a ScheduledMessage that's already delivered, somehow... so maybe that logic should just `return if delivered?` at the top?

**Comment by njvack** [comment]
Yes, that would be good.

Wow, that `elsif not self.schedule_day.participant.active?` is not my most shining line of code
